SELECT YEAR(OS.salesdate) Y, MONTH(OS.salesdate) M, UI.gender GENDER, COUNT(DISTINCT UI.userid)
FROM USERINFO UI, ONLINESALE OS
WHERE UI.userid = OS.user_id AND GENDER is not null
GROUP BY Y,M,GENDER
ORDER BY Y,M,GENDER;
