WITH RECURSIVE TIME AS(
    SELECT 0 as hour
    UNION ALL
    SELECT HOUR + 1 FROM time WHERE HOUR < 23)

SELECT time.HOUR, COUNT(ANIMAL_OUTS.datetime) AS COUNT
FROM time
LEFT JOIN ANIMAL_OUTS
ON time.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOUR
