-- 코드를 입력하세요
SELECT COUNT(*) FROM USER_INFO
WHERE JOINED < '2022-01-01' AND JOINED > '2020-12-31'; #21년도 가입자 수

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT O.USER_ID) PUCHASED_USERS,
ROUND((COUNT(DISTINCT O.USER_ID))/COUNT ,1) PUCHASED_RATIO
FROM ONLINE_SALE O
JOIN (SELECT USER_ID, COUNT(*) OVER() COUNT FROM USER_INFO
WHERE JOINED < '2022-01-01' 
      AND JOINED > '2020-12-31') T
ON O.USER_ID = T.USER_ID
GROUP BY DATE_FORMAT(SALES_DATE,'%Y-%m')
ORDER BY DATE_FORMAT(SALES_DATE,'%Y-%m') ASC; #21년도 가입자 중 판매데이터


-- 코드를 입력하세요
SELECT COUNT(*) FROM USER_INFO
WHERE JOINED < '2022-01-01' AND JOINED > '2020-12-31'; #21년도 가입자 수

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT O.USER_ID) PUCHASED_USERS,
ROUND((COUNT(DISTINCT O.USER_ID))/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021) ,1) PUCHASED_RATIO # 구매자 / 전체 회원수
FROM ONLINE_SALE O
JOIN (SELECT USER_ID, COUNT(*) OVER() COUNT FROM USER_INFO #COUNT OVER 전체 회원수
WHERE JOINED < '2022-01-01' 
      AND JOINED > '2020-12-31') T
ON O.USER_ID = T.USER_ID
GROUP BY DATE_FORMAT(SALES_DATE,'%Y-%m')
ORDER BY DATE_FORMAT(SALES_DATE,'%Y-%m') ASC; #21년도 가입자 중 판매데이터

//아래는 COUNT OVER 미사용
