SELECT AU.AUTHOR_ID, AU.AUTHOR_NAME, BK.CATEGORY, SUM(BS.SALES * BK.PRICE) AS SALES
  FROM BOOK BK, AUTHOR AU, BOOK_SALES BS
  WHERE DATE_FORMAT(BS.SALES_DATE,'%Y-%m') = '2022-01' AND
        BK.BOOK_ID = BS.BOOK_ID AND BK.AUTHOR_ID = AU.AUTHOR_ID
  GROUP BY AU.AUTHOR_ID, BK.CATEGORY
  ORDER BY AU.AUTHOR_ID ASC, BK.CATEGORY DESC;
